repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--install-types, --non-interactive, --explicit-package-bases, --check-untyped-defs]
