name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

  test-with-bioimage-core-conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        environment-file: dev/env_default.yaml
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: pip install --no-deps -e .
    - name: pytest-with-bioimage-core-conda
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  test-with-bioimage-core-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        environment-file: dev/env_default.yaml
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --force bioimageio.core
        pip install --no-deps git+https://github.com/bioimage-io/core-bioimage-io-python
        pip install --no-deps -e .
    - name: pytest-with-bioimage-core-main
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings
    - name: setup for workflow RDF verification
      if: matrix.python-version == 3.9
      shell: bash -l {0}
      run: mamba install -c conda-forge docstring_parser
    - name: verify generated workflow RDFs
      if: matrix.python-version == 3.9
      shell: bash -l {0}
      run: python scripts/generate_workflow_rdfs.py default --verify
    - name: MyPy all but env submodules other than default
      if: matrix.python-version == 3.9
      run: |
        mkdir -p .mypy-cache
        mypy --install-types --non-interactive --cache-dir .mypy-cache --explicit-package-bases --check-untyped-defs --exclude src/bioimageio/envs . 
        mypy --install-types --non-interactive --cache-dir .mypy-cache --explicit-package-bases --check-untyped-defs src/bioimageio/envs/default

  test-env-stardist:
    needs: test-with-bioimage-core-conda
    uses: bioimage-io/workflows-bioimage-io-python/.github/workflows/test-env.yaml@main
    with:
      env_name: stardist
      python_version: 3.7

  test-env-stardist-tf1:
    needs: test-with-bioimage-core-conda
    uses: bioimage-io/workflows-bioimage-io-python/.github/workflows/test-env.yaml@main
    with:
      env_name: stardist_tf1
      submodule_name: stardist
      python_version: 3.7

  conda-build:
    runs-on: ubuntu-latest
    needs: test-with-bioimage-core-conda
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        environment-file: false
        environment-name: build-env
        channels: conda-forge
        extra-specs: |
          boa
    - name: linux conda build
      shell: bash -l {0}
      run: |
        conda mambabuild -c conda-forge conda-recipe
