name: test env

on:
  workflow_call:
    inputs:
      env_name:
        description: "conda environment name"
        type: string
        required: true
      submodule_name:
        description: "bioimageio.workflows (environment dependent) submodule to test. Default: <env_name>"
        type: string
        required: false
        default: ''
      python_version:
        description: "python version to run test with"
        type: number
        required: true

jobs:
  test-env:
    name: test-env-${{ inputs.env_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        channel-priority: flexible
        activate-environment: ${{ inputs.env_name }}
        environment-file: dev/env_${{ inputs.env_name }}.yaml
        python-version: ${{ inputs.python_version }}
    - name: pytest
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings tests/test_${{ inputs.submodule_name || inputs.env_name }}
    - name: setup for workflow RDF verification
      shell: bash -l {0}
      run: mamba install -c conda-forge docstring_parser
    - name: verify generated workflow RDFs
      shell: bash -l {0}
      run: python scripts/generate_workflow_rdfs.py {{ inputs.env_name }} --verify
    - name: MyPy env submodule
      run: |
        mkdir -p .mypy-cache
        mypy --install-types --non-interactive --cache-dir .mypy-cache --explicit-package-bases --check-untyped-defs src/bioimageio/envs/${{ inputs.env_name }}
